threshold_days_hdfs: 150
hdfs_base_path: "/path/to/monitor_hdfs"

threshold_days_local: 30
local_base_path: "/var/log/myapp"

temp_storage_path: "/home/edgeuser/cleanup_framework"

permanent_exclusion_file: "/home/edgeuser/cleanup_framework/permanent_exclusions.txt"

email:
  host: "smtp.example.com"
  port: 587
  use_tls: true
  username: "sender@example.com"
  password: "YourPassword"
  subject: "Deletion Alert"
  body: |
    Hello Team,

    Please find attached the list of files scheduled for deletion in 4 days.
    If you need to exclude anything, please do so via the exclusion file or
    the Flask endpoint.

    Thank you.
  from: "sender@example.com"
  to:
    - "dev1@example.com"
    - "dev2@example.com"
  cc:
    - "manager@example.com"
